# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MinMaxRaster.ui'
#
# Created: Mon Jun 20 16:20:18 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MinMaxRaster(object):
    def setupUi(self, MinMaxRaster):
        MinMaxRaster.setObjectName(_fromUtf8("MinMaxRaster"))
        MinMaxRaster.resize(441, 413)
        self.tabWidget = QtGui.QTabWidget(MinMaxRaster)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 441, 411))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.General_tab = QtGui.QWidget()
        self.General_tab.setObjectName(_fromUtf8("General_tab"))
        self.layoutWidget = QtGui.QWidget(self.General_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 419, 365))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.DEM_label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DEM_label_2.sizePolicy().hasHeightForWidth())
        self.DEM_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DEM_label_2.setFont(font)
        self.DEM_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DEM_label_2.setObjectName(_fromUtf8("DEM_label_2"))
        self.verticalLayout_2.addWidget(self.DEM_label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.polygonLayerSelector = QtGui.QComboBox(self.layoutWidget)
        self.polygonLayerSelector.setEditable(False)
        self.polygonLayerSelector.setObjectName(_fromUtf8("polygonLayerSelector"))
        self.horizontalLayout_6.addWidget(self.polygonLayerSelector)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setBaseSize(QtCore.QSize(0, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.btn_BrowseForPolyFile = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_BrowseForPolyFile.sizePolicy().hasHeightForWidth())
        self.btn_BrowseForPolyFile.setSizePolicy(sizePolicy)
        self.btn_BrowseForPolyFile.setObjectName(_fromUtf8("btn_BrowseForPolyFile"))
        self.horizontalLayout_8.addWidget(self.btn_BrowseForPolyFile)
        self.input_polyFilePath = QtGui.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_polyFilePath.sizePolicy().hasHeightForWidth())
        self.input_polyFilePath.setSizePolicy(sizePolicy)
        self.input_polyFilePath.setMinimumSize(QtCore.QSize(0, 0))
        self.input_polyFilePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.input_polyFilePath.setObjectName(_fromUtf8("input_polyFilePath"))
        self.horizontalLayout_8.addWidget(self.input_polyFilePath)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.DEM_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DEM_label.sizePolicy().hasHeightForWidth())
        self.DEM_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DEM_label.setFont(font)
        self.DEM_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DEM_label.setObjectName(_fromUtf8("DEM_label"))
        self.verticalLayout.addWidget(self.DEM_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rasterLayerSelector = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rasterLayerSelector.sizePolicy().hasHeightForWidth())
        self.rasterLayerSelector.setSizePolicy(sizePolicy)
        self.rasterLayerSelector.setObjectName(_fromUtf8("rasterLayerSelector"))
        self.horizontalLayout_4.addWidget(self.rasterLayerSelector)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setBaseSize(QtCore.QSize(0, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_BrowseForDemFile = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_BrowseForDemFile.sizePolicy().hasHeightForWidth())
        self.btn_BrowseForDemFile.setSizePolicy(sizePolicy)
        self.btn_BrowseForDemFile.setObjectName(_fromUtf8("btn_BrowseForDemFile"))
        self.horizontalLayout_3.addWidget(self.btn_BrowseForDemFile)
        self.input_rasterFilePath = QtGui.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_rasterFilePath.sizePolicy().hasHeightForWidth())
        self.input_rasterFilePath.setSizePolicy(sizePolicy)
        self.input_rasterFilePath.setMinimumSize(QtCore.QSize(0, 0))
        self.input_rasterFilePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.input_rasterFilePath.setObjectName(_fromUtf8("input_rasterFilePath"))
        self.horizontalLayout_3.addWidget(self.input_rasterFilePath)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.DEM_label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DEM_label_5.sizePolicy().hasHeightForWidth())
        self.DEM_label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DEM_label_5.setFont(font)
        self.DEM_label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DEM_label_5.setObjectName(_fromUtf8("DEM_label_5"))
        self.verticalLayout_6.addWidget(self.DEM_label_5)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.btn_BrowseForOutputFile = QtGui.QPushButton(self.layoutWidget)
        self.btn_BrowseForOutputFile.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_BrowseForOutputFile.setObjectName(_fromUtf8("btn_BrowseForOutputFile"))
        self.horizontalLayout_20.addWidget(self.btn_BrowseForOutputFile)
        self.input_outputPath = QtGui.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_outputPath.sizePolicy().hasHeightForWidth())
        self.input_outputPath.setSizePolicy(sizePolicy)
        self.input_outputPath.setMinimumSize(QtCore.QSize(0, 0))
        self.input_outputPath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.input_outputPath.setObjectName(_fromUtf8("input_outputPath"))
        self.horizontalLayout_20.addWidget(self.input_outputPath)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_14.addWidget(self.label_4)
        self.OutputTypeSelector = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputTypeSelector.sizePolicy().hasHeightForWidth())
        self.OutputTypeSelector.setSizePolicy(sizePolicy)
        self.OutputTypeSelector.setEditable(False)
        self.OutputTypeSelector.setObjectName(_fromUtf8("OutputTypeSelector"))
        self.OutputTypeSelector.addItem(_fromUtf8(""))
        self.OutputTypeSelector.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.OutputTypeSelector)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_13.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.General_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.About_tab = QtGui.QWidget()
        self.About_tab.setObjectName(_fromUtf8("About_tab"))
        self.label_12 = QtGui.QLabel(self.About_tab)
        self.label_12.setGeometry(QtCore.QRect(30, 90, 351, 61))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.About_tab)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_18 = QtGui.QLabel(self.About_tab)
        self.label_18.setGeometry(QtCore.QRect(30, 160, 321, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget.addTab(self.About_tab, _fromUtf8(""))

        self.retranslateUi(MinMaxRaster)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MinMaxRaster.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MinMaxRaster.accept)
        QtCore.QMetaObject.connectSlotsByName(MinMaxRaster)

    def retranslateUi(self, MinMaxRaster):
        MinMaxRaster.setWindowTitle(_translate("MinMaxRaster", "MinMaxRaster", None))
        self.DEM_label_2.setText(_translate("MinMaxRaster", "Polygon Layer", None))
        self.label_3.setText(_translate("MinMaxRaster", "Select Map Layer", None))
        self.label_10.setText(_translate("MinMaxRaster", "Or Load File:", None))
        self.btn_BrowseForPolyFile.setText(_translate("MinMaxRaster", "Browse", None))
        self.DEM_label.setText(_translate("MinMaxRaster", "Digital Elevation Model (Raster)", None))
        self.label.setText(_translate("MinMaxRaster", "Select Map Layer", None))
        self.label_9.setText(_translate("MinMaxRaster", "Or Load File:", None))
        self.btn_BrowseForDemFile.setText(_translate("MinMaxRaster", "Browse", None))
        self.DEM_label_5.setText(_translate("MinMaxRaster", "Output File", None))
        self.btn_BrowseForOutputFile.setText(_translate("MinMaxRaster", "Browse", None))
        self.label_4.setText(_translate("MinMaxRaster", "Output Type:", None))
        self.OutputTypeSelector.setItemText(0, _translate("MinMaxRaster", "Highest Points in Polygon", None))
        self.OutputTypeSelector.setItemText(1, _translate("MinMaxRaster", "Lowest Points in Polygon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General_tab), _translate("MinMaxRaster", "Setup", None))
        self.textBrowser_2.setHtml(_translate("MinMaxRaster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Polygon layer:</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> A Vector layer containing polygons within which to find the highest and lowest points. For instance a layer representing buildings</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Digital Elevation Model:</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> A raster layer representing a digital elevation model</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Output file:</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">  A .shp file containing a field for highest as well as lowest points in polygons</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MinMaxRaster", "Help", None))
        self.label_12.setText(_translate("MinMaxRaster", "Developed by Jakob Hvitnov\n"
"Roskilde University\n"
"Denmark", None))
        self.label_13.setText(_translate("MinMaxRaster", "Version 0.0.1", None))
        self.label_18.setText(_translate("MinMaxRaster", "Parts inspired by Zoran Čučković\'s vievshed Plugin", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.About_tab), _translate("MinMaxRaster", "About", None))

